// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Baha Bouali"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck": {
            "get": {
                "tags": [
                    "healthcheck"
                ],
                "summary": "Gives a brief healthcheck details about the applications",
                "responses": {}
            }
        },
        "/movies": {
            "get": {
                "tags": [
                    "movies"
                ],
                "summary": "List all movies with each one's details",
                "responses": {}
            },
            "post": {
                "tags": [
                    "movies"
                ],
                "summary": "Add a new movie",
                "responses": {}
            }
        },
        "/movies/{id}": {
            "get": {
                "tags": [
                    "movies"
                ],
                "summary": "Show a specific movie details",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "movies"
                ],
                "summary": "Delete an existing movie",
                "responses": {}
            },
            "patch": {
                "tags": [
                    "movies"
                ],
                "summary": "Update an existing movie",
                "responses": {}
            }
        },
        "/users": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register a new user",
                "responses": {}
            }
        },
        "/users/activated": {
            "put": {
                "tags": [
                    "users"
                ],
                "summary": "Activate a new added user",
                "responses": {}
            }
        },
        "/users/auth": {
            "post": {
                "tags": [
                    "users"
                ],
                "summary": "Authenticate a user",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4000",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Movie information API",
	Description:      "This is a simple API for accessing and managing movie information, inspired by the Open Movie Database API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
