basePath: /v1
host: localhost:4000
info:
  contact:
    name: Baha Bouali
  description: This is a simple API for accessing and managing movie information,
    inspired by the Open Movie Database API.
  title: Movie information API
  version: "1.0"
paths: {}
swagger: "2.0"
